Say hello to Android.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 #############################################################################
 ##
 ## Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
@@ -51,6 +52,16 @@ relpath=`dirname $0`
 relpath=`(cd "$relpath"; /bin/pwd)`
 # the current directory is the "build tree" or "object tree"
 outpath=`/bin/pwd`
+
+# Fix the paths. pwd -W returns C:/whatever
+if [ "msys" = "$OSTYPE" ]; then
+    pushd . > /dev/null
+    cd $relpath
+    relpath=`pwd -W`
+    cd $outpath
+    outpath=`pwd -W`
+    popd > /dev/null
+fi
 
 #license file location
 LICENSE_FILE="$QT_LICENSE_FILE"
@@ -351,6 +362,15 @@ UNAME_MACHINE=`(uname -m) 2>/dev/null` || UNAME_MACHINE=unknown
 UNAME_RELEASE=`(uname -r) 2>/dev/null` || UNAME_RELEASE=unknown
 UNAME_SYSTEM=`(uname -s) 2>/dev/null`  || UNAME_SYSTEM=unknown
 UNAME_VERSION=`(uname -v) 2>/dev/null` || UNAME_VERSION=unknown
+# early detection of Android, needed for linuxfb and linuxtp.
+XPLATFORM_ANDROID=no
+for ARG in $@
+do
+    if [ "$ARG" = "android-g++" ]; then
+        XPLATFORM_ANDROID=yes
+    fi
+done
+echo "XPLATFORM_ANDROID=$XPLATFORM_ANDROID"
 
 # detect the "echo without newline" style. usage: echo $ECHO_N "<string>$ECHO_C"
 if echo '\c' | grep '\c' >/dev/null; then
@@ -368,6 +388,13 @@ PLATFORM_MAC=no
 if [ -d /System/Library/Frameworks/Carbon.framework ]; then
     BUILD_ON_MAC=yes
     PLATFORM_MAC=maybe
+fi
+
+BUILD_ON_MSYS=no
+if [ "msys" = "$OSTYPE" ]; then
+    BUILD_ON_MSYS=yes
+else
+    BUILD_ON_MSYS=no
 fi
 
 #-----------------------------------------------------------------------------
@@ -774,7 +801,7 @@ CFG_SSE=auto
 CFG_FONTCONFIG=auto
 CFG_LIBFREETYPE=auto
 CFG_SQL_AVAILABLE=
-QT_DEFAULT_BUILD_PARTS="libs tools examples"
+QT_DEFAULT_BUILD_PARTS="libs tools"
 CFG_BUILD_PARTS=""
 CFG_NOBUILD_PARTS=""
 CFG_RELEASE_QMAKE=no
@@ -874,6 +901,9 @@ CFG_FORCE_ASSERTS=no
 CFG_PCRE=auto
 QPA_PLATFORM_GUARD=yes
 CFG_CXX11=auto
+CFG_OPENSSL_SOURCE=
+CFG_MS_BITFIELDS=no
+CFG_CROSS_QMAKE=
 
 # initalize variables used for installation
 QT_INSTALL_PREFIX=
@@ -1042,6 +1072,11 @@ while [ "$#" -gt 0 ]; do
             VAL=$1
         fi
 	;;
+    -openssl-source)
+        VAR="openssl-source"
+        shift
+        VAL="$1"
+    ;;
     -hostprefix)
         VAR=`echo $1 | sed "s,^-\(.*\),\1,"`
         # this option may or may not be followed by an argument
@@ -1059,6 +1094,11 @@ while [ "$#" -gt 0 ]; do
         ;;
     -qtlibinfix)
         VAR="qtlibinfix"
+        shift
+        VAL="$1"
+        ;;
+    -cross-qmake)
+        VAR="cross-qmake"
         shift
         VAL="$1"
         ;;
@@ -1295,7 +1335,7 @@ while [ "$#" -gt 0 ]; do
             UNKNOWN_OPT=yes
         fi
 	;;
-    arch|host-arch)
+    host-arch)
         OPT_OBSOLETE_HOST_ARG=yes
         ;;
     harfbuzz)
@@ -1391,6 +1431,9 @@ while [ "$#" -gt 0 ]; do
 		QTCONFIG_CONFIG="$QTCONFIG_CONFIG $NATIVE_64_ARCH"
             fi
             ;;
+        win32-g++)
+            PLATFORM=win32-g++
+            ;;
         esac
         ;;
     xplatform)
@@ -1401,6 +1444,9 @@ while [ "$#" -gt 0 ]; do
             CFG_REDUCE_EXPORTS=no
             ;;
         esac
+        ;;
+    arch)
+        CFG_ARCH="$VAL"
         ;;
     device)
         XPLATFORM=`resolveDeviceMkspec $VAL`
@@ -1856,8 +1902,8 @@ while [ "$#" -gt 0 ]; do
     dbus)
         if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ] || [ "$VAL" = "linked" ]; then
             CFG_DBUS="$VAL"
-	elif [ "$VAL" = "runtime" ]; then
-	    CFG_DBUS="yes"
+        elif [ "$VAL" = "runtime" ]; then
+            CFG_DBUS="yes"
         else
             UNKNOWN_OPT=yes
         fi
@@ -1896,6 +1942,9 @@ while [ "$#" -gt 0 ]; do
         else
             UNKNOWN_OPT=yes
         fi
+        ;;
+    openssl-source)
+        CFG_OPENSSL_SOURCE="$VAL"
         ;;
     qml-debug)
         if [ "$VAL" = "yes" ]; then
@@ -2109,9 +2158,20 @@ while [ "$#" -gt 0 ]; do
             UNKNOWN_OPT=yes
         fi
         ;;
-    system-proxies)
+    cross-qmake)
+        CFG_CROSS_QMAKE=$VAL
+        QT_CROSS_COMPILE=yes
+        ;;
+    ms-bitfields)
         if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
-            CFG_SYSTEM_PROXIES="$VAL"
+            CFG_MS_BITFIELDS="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    BUILD_ON_MSYS)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            BUILD_ON_MSYS="$VAL"
         else
             UNKNOWN_OPT=yes
         fi
@@ -2208,6 +2268,22 @@ if [ "$CFG_SILENT" = "yes" ]; then
     QMAKE_CONFIG="$QMAKE_CONFIG silent"
 fi
 
+if [ "$PLATFORM" = "win32-g++" ] || [ "$XPLATFORM" = "win32-g++" ] && [ "$CFG_MS_BITFIELDS" = "yes" ]; then
+    QMAKE_CONFIG="$QMAKE_CONFIG ms_bitfields"
+fi
+
+# Without this hack, OpenGLES2 test fails for Android:
+# (undefined reference to `android::egl_get_image_for_current_context(void*))')
+# See http://blog.vlad1.com/2010/03/19/things-i-learned-today-android-opengl-edition-2/
+# Hack is to add -Wl,-allow-shlib-undefined. Should do this for Android only though, but
+# at the minute I'm not sure if we're QPA,desktop or all of the above, so I've applied
+# it globally to all of the OpenGLES2 compile-tests. Very unlikely that it'd trip up
+# other platforms too.
+
+if [ "$XPLATFORM_ANDROID" = "yes" ]; then
+    ANDROID_GLES2_LFLAGS=-Wl,-allow-shlib-undefined
+fi
+
 # if the source tree is different from the build tree,
 # symlink or copy part of the sources
 if [ "$OPT_SHADOW" = "yes" ]; then
@@ -2252,7 +2328,11 @@ if [ "$OPT_SHADOW" = "yes" ]; then
     # symlink the mkspecs directory
     mkdir -p "$outpath/mkspecs"
     rm -rf "$outpath"/mkspecs/*
-    ln -s "$relpath"/mkspecs/* "$outpath/mkspecs"
+    if [ "$OSTYPE" = "msys" ] ; then
+        cp -rf "$relpath"/mkspecs "$outpath/"
+    else
+        ln -s "$relpath"/mkspecs/* "$outpath/mkspecs/"
+    fi
 
     ShadowMkspecs()
     {
@@ -2498,6 +2578,7 @@ fi
 case `basename "$XPLATFORM"` in win32-g++*) XPLATFORM_MINGW=yes;; esac
 case "$XPLATFORM" in *-maemo*) XPLATFORM_MAEMO=yes;; esac
 case "$XPLATFORM" in *qnx-*|*blackberry-*) XPLATFORM_QNX=yes;; esac
+case "$XPLATFORM" in *android*) XPLATFORM_ANDROID=yes;; esac
 
 if [ -d "$PLATFORM" ]; then
   QMAKESPEC="$PLATFORM"
@@ -2509,7 +2590,7 @@ if [ -d "$XPLATFORM" ]; then
 else
   XQMAKESPEC="$relpath/mkspecs/${XPLATFORM}"
 fi
-if [ "$PLATFORM" != "$XPLATFORM" ]; then
+if [ "$PLATFORM" != "$XPLATFORM" ] || [ "$QT_CROSS_COMPILE" = "yes" ]; then
     QT_CROSS_COMPILE=yes
     QMAKE_CONFIG="$QMAKE_CONFIG cross_compile"
     QTCONFIG_CONFIG="$QTCONFIG_CONFIG cross_compile"
@@ -2630,6 +2711,19 @@ fi
 QMAKE_CONF_COMPILER=`getXQMakeConf QMAKE_CXX`
 
 TEST_COMPILER=$QMAKE_CONF_COMPILER
+
+if [ "$XPLATFORM_ANDROID" = "yes" ] ; then
+    # Repeat what mkspecs for android does. This is horrible, but I can't see a way around it given what getQMakeConf does.
+    NDK_TOOLCHAIN_PATH=$ANDROID_NDK_ROOT/toolchains/$ANDROID_NDK_TOOLCHAIN_PREFIX-$ANDROID_NDK_TOOLCHAIN_VERSION/prebuilt/$ANDROID_NDK_HOST
+    NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi
+    # Replace all occourances of $$(EXAMPLE_VARIABLE) from qmake.conf with ${EXAMPLE_VARIABLE}
+    #  so we can eval it from shell script.
+    QMAKE_CONF_COMPILER=$NDK_TOOLCHAIN_PATH/$(echo "$QMAKE_CONF_COMPILER" | sed 's:\$\$(\([a-zA-Z_]*\)):\${\1}:g')
+
+    eval QMAKE_CONF_COMPILER=$QMAKE_CONF_COMPILER
+    TEST_COMPILER="$QMAKE_CONF_COMPILER --sysroot=$ANDROID_NDK_ROOT/platforms/android-5/arch-arm/"
+fi
+
 if [ "$XPLATFORM_SYMBIAN_SBSV2" = "no" ]; then
     if [ -z "$TEST_COMPILER" ]; then
         echo "ERROR: Cannot set the compiler for the configuration tests"
@@ -3485,6 +3579,12 @@ elif [ "$Edition" != "OpenSource" ]; then
             more "$outpath/LICENSE"
         fi
     done
+    MAC_CONFIG_TEST_COMMANDLINE="-arch i386 -arch x86_64"
+    CFG_MAC_ARCHS="x86 x86_64"
+fi
+
+if [ "$CFG_HOST_ARCH" = "macosx" ]; then
+    CFG_MAC_ARCHS="x86 x86_64"
 fi
 
 # this should be moved somewhere else
@@ -3611,7 +3711,11 @@ if true; then ###[ '!' -f "$outpath/bin/qmake" ];
 #           if which qmake >/dev/null 2>&1 && [ -f qmake/qmake.pro ]; then
 #               (cd qmake && qmake) >/dev/null 2>&1 && continue
 #           fi
-            in_mkfile="${mkfile}.unix"
+            if [ "$BUILD_ON_MSYS" = "yes" ]; then
+                in_mkfile="${mkfile}.win32-g++-sh"
+            else
+                in_mkfile="${mkfile}.unix"
+            fi
         fi
         in_mkfile="$relpath/qmake/$in_mkfile"
         mkfile="$outpath/qmake/$mkfile"
@@ -3828,7 +3932,7 @@ fi
 rm -f "$OUTFILE" 2>/dev/null
 [ -z "$CFG_ARCH" ] && CFG_ARCH="unknown"
 
-if [ "$QMAKESPEC" != "$XQMAKESPEC" ]; then
+if [ "$QMAKESPEC" != "$XQMAKESPEC" && "$CFG_ARCH" != "unknown"]; then
     # Do the same test again, using the host compiler
     SYSROOT_FLAG= "$unixtests/arch.test" "$QMAKESPEC" $OPT_VERBOSE "$relpath" "$outpath" "$OUTFILE" "CFG_HOST" $MAC_SDK_FLAG
     if [ $? -eq 0 ]; then
@@ -4041,6 +4145,14 @@ if [ "$CFG_ZLIB" = "auto" ]; then
     fi
 fi
 
+case "$XPLATFORM" in *android*)
+    QMakeVar add styles "android"
+    if compileTest unix/ipc_android "ipc_android"; then
+        QT_CONFIG="$QT_CONFIG ashmem"
+    fi
+esac
+
+
 if [ "$CFG_LARGEFILE" = "auto" ]; then
     #Large files should be enabled for all Linux systems
     CFG_LARGEFILE=yes
@@ -4114,12 +4226,12 @@ for _SQLDR in $CFG_SQL_AVAILABLE; do
         case $_SQLDR in
         mysql)
             if [ "$CFG_SQL_mysql" != "no" ]; then
-		[ -z "$CFG_MYSQL_CONFIG" ] && CFG_MYSQL_CONFIG=`"$WHICH" mysql_config`
+                [ -z "$CFG_MYSQL_CONFIG" ] && CFG_MYSQL_CONFIG=`"$WHICH" mysql_config`
                 if [ -x "$CFG_MYSQL_CONFIG" ]; then
                     QT_CFLAGS_MYSQL=`$CFG_MYSQL_CONFIG --include 2>/dev/null | filterIncludeOptions`
                     QT_LFLAGS_MYSQL_R=`$CFG_MYSQL_CONFIG --libs_r 2>/dev/null | filterLibraryOptions`
                     QT_LFLAGS_MYSQL=`$CFG_MYSQL_CONFIG --libs 2>/dev/null | filterLibraryOptions`
-		    QT_MYSQL_VERSION=`$CFG_MYSQL_CONFIG --version 2>/dev/null`
+                    QT_MYSQL_VERSION=`$CFG_MYSQL_CONFIG --version 2>/dev/null`
                     QT_MYSQL_VERSION_MAJOR=`echo $QT_MYSQL_VERSION | cut -d . -f 1`
                 fi
                 if [ -n "$QT_MYSQL_VERSION" ] && [ "$QT_MYSQL_VERSION_MAJOR" -lt 4 ]; then
@@ -4131,9 +4243,9 @@ for _SQLDR in $CFG_SQL_AVAILABLE; do
                         exit 101
                     else
                         CFG_SQL_mysql="no"
-			QT_LFLAGS_MYSQL=""
-			QT_LFLAGS_MYSQL_R=""
-			QT_CFLAGS_MYSQL=""
+                        QT_LFLAGS_MYSQL=""
+                        QT_LFLAGS_MYSQL_R=""
+                        QT_CFLAGS_MYSQL=""
                     fi
                 else
                     if compileTest unix/mysql_r "MySQL (thread-safe)" $QT_LFLAGS_MYSQL_R $QT_CFLAGS_MYSQL; then
@@ -5145,20 +5257,24 @@ fi
 
 # detect OpenSSL
 if [ "$CFG_OPENSSL" != "no" ]; then
-    if compileTest unix/openssl "OpenSSL"; then
-        if [ "$CFG_OPENSSL" = "auto" ]; then
-            CFG_OPENSSL=yes
+    if [ "$XPLATFORM_ANDROID" != "yes" ]; then
+        if compileTest unix/openssl "OpenSSL"; then
+            if [ "$CFG_OPENSSL" = "auto" ]; then
+                CFG_OPENSSL=yes
+            fi
+        else
+            if ( [ "$CFG_OPENSSL" = "yes" ] || [ "$CFG_OPENSSL" = "linked" ] ) && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]  && [ "$XPLATFORM_ANDROID" = "no" ]; then
+                echo "OpenSSL support cannot be enabled due to functionality tests!"
+                echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                echo " If you believe this message is in error you may use the continue"
+                echo " switch (-continue) to $0 to continue."
+                exit 101
+            else
+                CFG_OPENSSL=no
+            fi
         fi
     else
-        if ( [ "$CFG_OPENSSL" = "yes" ] || [ "$CFG_OPENSSL" = "linked" ] ) && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
-            echo "OpenSSL support cannot be enabled due to functionality tests!"
-            echo " Turn on verbose messaging (-v) to $0 to see the final report."
-            echo " If you believe this message is in error you may use the continue"
-            echo " switch (-continue) to $0 to continue."
-            exit 101
-        else
-            CFG_OPENSSL=no
-        fi
+        CFG_OPENSSL=yes
     fi
 fi
 
@@ -5558,7 +5674,7 @@ case "$XPLATFORM" in
 	# the assembly it generates cannot be compiled
 
 	# Check gcc's version
-	case "$(${QMAKE_CONF_COMPILER} -dumpversion)" in
+	case "${QMAKE_CONF_COMPILER} -dumpversion" in
 	    4*)
 		;;
 	    3.4*)
@@ -5579,15 +5695,17 @@ case "$XPLATFORM" in
 	;;
     *-g++*)
 	# Check gcc's version
-	case "$(${QMAKE_CONF_COMPILER} -dumpversion)" in
+	case "${QMAKE_CONF_COMPILER} -dumpversion" in
 	    4*|3.4*)
 		;;
             3.3*)
                 canBuildWebKit="no"
                 ;;
 	    *)
-		canBuildWebKit="no"
-		canBuildQtXmlPatterns="no"
+        if [ "$XPLATFORM_ANDROID" != "yes" ]; then
+            canBuildWebKit="no"
+            canBuildQtXmlPatterns="no"
+        fi
 		;;
 	esac
 	;;
@@ -5875,7 +5993,6 @@ QMakeVar set sql-plugins "$SQL_PLUGINS"
 [ "$CFG_NIS" = "no" ]        && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_NIS"
 [ "$CFG_OPENSSL" = "no" ]    && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_OPENSSL QT_NO_SSL"
 [ "$CFG_OPENSSL" = "linked" ]&& QCONFIG_FLAGS="$QCONFIG_FLAGS QT_LINKED_OPENSSL"
-
 [ "$CFG_SM" = "no" ]         && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_SESSIONMANAGER"
 [ "$CFG_XCURSOR" = "no" ]    && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_XCURSOR"
 [ "$CFG_XFIXES" = "no" ]     && QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_XFIXES"
